FROM node:22.2.0-alpine as build-stage

# To build the image: 
# docker build --tag=notepad-fe --file Dockerfile.frontend --target=release-stage .

# copy the frontend code
RUN mkdir -p /app/
WORKDIR /app
ADD packages/client/ /app/
RUN yarn install
RUN yarn build

FROM lipanski/docker-static-website:latest AS release-stage
COPY --from=build-stage /app/dist/ .
EXPOSE 3000
CMD ["/busybox", "httpd", "-f", "-v", "-p", "3000", "-c", "httpd.conf"]
