// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/edu/umass/cs/pram/proto/pram_packet.proto
// Protobuf Java Version: 4.28.2

package edu.umass.cs.pram.proto;

public final class PramPacketProto {
  private PramPacketProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      PramPacketProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PramReadPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pram.PramReadPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 packet_id = 1;</code>
     * @return The packetId.
     */
    long getPacketId();

    /**
     * <code>bytes encoded_request = 2;</code>
     * @return The encodedRequest.
     */
    com.google.protobuf.ByteString getEncodedRequest();
  }
  /**
   * Protobuf type {@code pram.PramReadPacket}
   */
  public static final class PramReadPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pram.PramReadPacket)
      PramReadPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        PramReadPacket.class.getName());
    }
    // Use PramReadPacket.newBuilder() to construct.
    private PramReadPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PramReadPacket() {
      encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramReadPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramReadPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.class, edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.Builder.class);
    }

    public static final int PACKET_ID_FIELD_NUMBER = 1;
    private long packetId_ = 0L;
    /**
     * <code>int64 packet_id = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public long getPacketId() {
      return packetId_;
    }

    public static final int ENCODED_REQUEST_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encoded_request = 2;</code>
     * @return The encodedRequest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncodedRequest() {
      return encodedRequest_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0L) {
        output.writeInt64(1, packetId_);
      }
      if (!encodedRequest_.isEmpty()) {
        output.writeBytes(2, encodedRequest_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packetId_);
      }
      if (!encodedRequest_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encodedRequest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket)) {
        return super.equals(obj);
      }
      edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket other = (edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (!getEncodedRequest()
          .equals(other.getEncodedRequest())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketId());
      hash = (37 * hash) + ENCODED_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getEncodedRequest().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pram.PramReadPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pram.PramReadPacket)
        edu.umass.cs.pram.proto.PramPacketProto.PramReadPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramReadPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramReadPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.class, edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.Builder.class);
      }

      // Construct using edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        packetId_ = 0L;
        encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramReadPacket_descriptor;
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket getDefaultInstanceForType() {
        return edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.getDefaultInstance();
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket build() {
        edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket buildPartial() {
        edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket result = new edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packetId_ = packetId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.encodedRequest_ = encodedRequest_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket) {
          return mergeFrom((edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket other) {
        if (other == edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket.getDefaultInstance()) return this;
        if (other.getPacketId() != 0L) {
          setPacketId(other.getPacketId());
        }
        if (other.getEncodedRequest() != com.google.protobuf.ByteString.EMPTY) {
          setEncodedRequest(other.getEncodedRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                packetId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                encodedRequest_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long packetId_ ;
      /**
       * <code>int64 packet_id = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public long getPacketId() {
        return packetId_;
      }
      /**
       * <code>int64 packet_id = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(long value) {

        packetId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packet_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encoded_request = 2;</code>
       * @return The encodedRequest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncodedRequest() {
        return encodedRequest_;
      }
      /**
       * <code>bytes encoded_request = 2;</code>
       * @param value The encodedRequest to set.
       * @return This builder for chaining.
       */
      public Builder setEncodedRequest(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encodedRequest_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encoded_request = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncodedRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encodedRequest_ = getDefaultInstance().getEncodedRequest();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pram.PramReadPacket)
    }

    // @@protoc_insertion_point(class_scope:pram.PramReadPacket)
    private static final edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket();
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PramReadPacket>
        PARSER = new com.google.protobuf.AbstractParser<PramReadPacket>() {
      @java.lang.Override
      public PramReadPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PramReadPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PramReadPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.umass.cs.pram.proto.PramPacketProto.PramReadPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PramWritePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pram.PramWritePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 packet_id = 1;</code>
     * @return The packetId.
     */
    long getPacketId();

    /**
     * <code>bytes encoded_request = 2;</code>
     * @return The encodedRequest.
     */
    com.google.protobuf.ByteString getEncodedRequest();
  }
  /**
   * Protobuf type {@code pram.PramWritePacket}
   */
  public static final class PramWritePacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pram.PramWritePacket)
      PramWritePacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        PramWritePacket.class.getName());
    }
    // Use PramWritePacket.newBuilder() to construct.
    private PramWritePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PramWritePacket() {
      encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWritePacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWritePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.class, edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.Builder.class);
    }

    public static final int PACKET_ID_FIELD_NUMBER = 1;
    private long packetId_ = 0L;
    /**
     * <code>int64 packet_id = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public long getPacketId() {
      return packetId_;
    }

    public static final int ENCODED_REQUEST_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encoded_request = 2;</code>
     * @return The encodedRequest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncodedRequest() {
      return encodedRequest_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0L) {
        output.writeInt64(1, packetId_);
      }
      if (!encodedRequest_.isEmpty()) {
        output.writeBytes(2, encodedRequest_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packetId_);
      }
      if (!encodedRequest_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, encodedRequest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket)) {
        return super.equals(obj);
      }
      edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket other = (edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (!getEncodedRequest()
          .equals(other.getEncodedRequest())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketId());
      hash = (37 * hash) + ENCODED_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getEncodedRequest().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pram.PramWritePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pram.PramWritePacket)
        edu.umass.cs.pram.proto.PramPacketProto.PramWritePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWritePacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWritePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.class, edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.Builder.class);
      }

      // Construct using edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        packetId_ = 0L;
        encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWritePacket_descriptor;
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket getDefaultInstanceForType() {
        return edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.getDefaultInstance();
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket build() {
        edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket buildPartial() {
        edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket result = new edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packetId_ = packetId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.encodedRequest_ = encodedRequest_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket) {
          return mergeFrom((edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket other) {
        if (other == edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket.getDefaultInstance()) return this;
        if (other.getPacketId() != 0L) {
          setPacketId(other.getPacketId());
        }
        if (other.getEncodedRequest() != com.google.protobuf.ByteString.EMPTY) {
          setEncodedRequest(other.getEncodedRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                packetId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                encodedRequest_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long packetId_ ;
      /**
       * <code>int64 packet_id = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public long getPacketId() {
        return packetId_;
      }
      /**
       * <code>int64 packet_id = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(long value) {

        packetId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packet_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encoded_request = 2;</code>
       * @return The encodedRequest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncodedRequest() {
        return encodedRequest_;
      }
      /**
       * <code>bytes encoded_request = 2;</code>
       * @param value The encodedRequest to set.
       * @return This builder for chaining.
       */
      public Builder setEncodedRequest(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encodedRequest_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encoded_request = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncodedRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        encodedRequest_ = getDefaultInstance().getEncodedRequest();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pram.PramWritePacket)
    }

    // @@protoc_insertion_point(class_scope:pram.PramWritePacket)
    private static final edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket();
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PramWritePacket>
        PARSER = new com.google.protobuf.AbstractParser<PramWritePacket>() {
      @java.lang.Override
      public PramWritePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PramWritePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PramWritePacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.umass.cs.pram.proto.PramPacketProto.PramWritePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PramWriteAfterPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pram.PramWriteAfterPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 packet_id = 1;</code>
     * @return The packetId.
     */
    long getPacketId();

    /**
     * <code>string sender_node_id = 2;</code>
     * @return The senderNodeId.
     */
    java.lang.String getSenderNodeId();
    /**
     * <code>string sender_node_id = 2;</code>
     * @return The bytes for senderNodeId.
     */
    com.google.protobuf.ByteString
        getSenderNodeIdBytes();

    /**
     * <code>bytes encoded_request = 3;</code>
     * @return The encodedRequest.
     */
    com.google.protobuf.ByteString getEncodedRequest();
  }
  /**
   * Protobuf type {@code pram.PramWriteAfterPacket}
   */
  public static final class PramWriteAfterPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pram.PramWriteAfterPacket)
      PramWriteAfterPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        PramWriteAfterPacket.class.getName());
    }
    // Use PramWriteAfterPacket.newBuilder() to construct.
    private PramWriteAfterPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PramWriteAfterPacket() {
      senderNodeId_ = "";
      encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWriteAfterPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWriteAfterPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.class, edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.Builder.class);
    }

    public static final int PACKET_ID_FIELD_NUMBER = 1;
    private long packetId_ = 0L;
    /**
     * <code>int64 packet_id = 1;</code>
     * @return The packetId.
     */
    @java.lang.Override
    public long getPacketId() {
      return packetId_;
    }

    public static final int SENDER_NODE_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object senderNodeId_ = "";
    /**
     * <code>string sender_node_id = 2;</code>
     * @return The senderNodeId.
     */
    @java.lang.Override
    public java.lang.String getSenderNodeId() {
      java.lang.Object ref = senderNodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderNodeId_ = s;
        return s;
      }
    }
    /**
     * <code>string sender_node_id = 2;</code>
     * @return The bytes for senderNodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderNodeIdBytes() {
      java.lang.Object ref = senderNodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderNodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENCODED_REQUEST_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes encoded_request = 3;</code>
     * @return The encodedRequest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncodedRequest() {
      return encodedRequest_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (packetId_ != 0L) {
        output.writeInt64(1, packetId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderNodeId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, senderNodeId_);
      }
      if (!encodedRequest_.isEmpty()) {
        output.writeBytes(3, encodedRequest_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (packetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, packetId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(senderNodeId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, senderNodeId_);
      }
      if (!encodedRequest_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, encodedRequest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket)) {
        return super.equals(obj);
      }
      edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket other = (edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket) obj;

      if (getPacketId()
          != other.getPacketId()) return false;
      if (!getSenderNodeId()
          .equals(other.getSenderNodeId())) return false;
      if (!getEncodedRequest()
          .equals(other.getEncodedRequest())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PACKET_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPacketId());
      hash = (37 * hash) + SENDER_NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSenderNodeId().hashCode();
      hash = (37 * hash) + ENCODED_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getEncodedRequest().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pram.PramWriteAfterPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pram.PramWriteAfterPacket)
        edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWriteAfterPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWriteAfterPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.class, edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.Builder.class);
      }

      // Construct using edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        packetId_ = 0L;
        senderNodeId_ = "";
        encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.umass.cs.pram.proto.PramPacketProto.internal_static_pram_PramWriteAfterPacket_descriptor;
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket getDefaultInstanceForType() {
        return edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.getDefaultInstance();
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket build() {
        edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket buildPartial() {
        edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket result = new edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.packetId_ = packetId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.senderNodeId_ = senderNodeId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.encodedRequest_ = encodedRequest_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket) {
          return mergeFrom((edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket other) {
        if (other == edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket.getDefaultInstance()) return this;
        if (other.getPacketId() != 0L) {
          setPacketId(other.getPacketId());
        }
        if (!other.getSenderNodeId().isEmpty()) {
          senderNodeId_ = other.senderNodeId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getEncodedRequest() != com.google.protobuf.ByteString.EMPTY) {
          setEncodedRequest(other.getEncodedRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                packetId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                senderNodeId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                encodedRequest_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long packetId_ ;
      /**
       * <code>int64 packet_id = 1;</code>
       * @return The packetId.
       */
      @java.lang.Override
      public long getPacketId() {
        return packetId_;
      }
      /**
       * <code>int64 packet_id = 1;</code>
       * @param value The packetId to set.
       * @return This builder for chaining.
       */
      public Builder setPacketId(long value) {

        packetId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 packet_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object senderNodeId_ = "";
      /**
       * <code>string sender_node_id = 2;</code>
       * @return The senderNodeId.
       */
      public java.lang.String getSenderNodeId() {
        java.lang.Object ref = senderNodeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senderNodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender_node_id = 2;</code>
       * @return The bytes for senderNodeId.
       */
      public com.google.protobuf.ByteString
          getSenderNodeIdBytes() {
        java.lang.Object ref = senderNodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderNodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender_node_id = 2;</code>
       * @param value The senderNodeId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNodeId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        senderNodeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string sender_node_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderNodeId() {
        senderNodeId_ = getDefaultInstance().getSenderNodeId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string sender_node_id = 2;</code>
       * @param value The bytes for senderNodeId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        senderNodeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString encodedRequest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes encoded_request = 3;</code>
       * @return The encodedRequest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncodedRequest() {
        return encodedRequest_;
      }
      /**
       * <code>bytes encoded_request = 3;</code>
       * @param value The encodedRequest to set.
       * @return This builder for chaining.
       */
      public Builder setEncodedRequest(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        encodedRequest_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes encoded_request = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncodedRequest() {
        bitField0_ = (bitField0_ & ~0x00000004);
        encodedRequest_ = getDefaultInstance().getEncodedRequest();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pram.PramWriteAfterPacket)
    }

    // @@protoc_insertion_point(class_scope:pram.PramWriteAfterPacket)
    private static final edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket();
    }

    public static edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PramWriteAfterPacket>
        PARSER = new com.google.protobuf.AbstractParser<PramWriteAfterPacket>() {
      @java.lang.Override
      public PramWriteAfterPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PramWriteAfterPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PramWriteAfterPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public edu.umass.cs.pram.proto.PramPacketProto.PramWriteAfterPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pram_PramReadPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pram_PramReadPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pram_PramWritePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pram_PramWritePacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pram_PramWriteAfterPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pram_PramWriteAfterPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/edu/umass/cs/pram/proto/pram_packe" +
      "t.proto\022\004pram\"<\n\016PramReadPacket\022\021\n\tpacke" +
      "t_id\030\001 \001(\003\022\027\n\017encoded_request\030\002 \001(\014\"=\n\017P" +
      "ramWritePacket\022\021\n\tpacket_id\030\001 \001(\003\022\027\n\017enc" +
      "oded_request\030\002 \001(\014\"Z\n\024PramWriteAfterPack" +
      "et\022\021\n\tpacket_id\030\001 \001(\003\022\026\n\016sender_node_id\030" +
      "\002 \001(\t\022\027\n\017encoded_request\030\003 \001(\014B*\n\027edu.um" +
      "ass.cs.pram.protoB\017PramPacketProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pram_PramReadPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pram_PramReadPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pram_PramReadPacket_descriptor,
        new java.lang.String[] { "PacketId", "EncodedRequest", });
    internal_static_pram_PramWritePacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pram_PramWritePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pram_PramWritePacket_descriptor,
        new java.lang.String[] { "PacketId", "EncodedRequest", });
    internal_static_pram_PramWriteAfterPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pram_PramWriteAfterPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pram_PramWriteAfterPacket_descriptor,
        new java.lang.String[] { "PacketId", "SenderNodeId", "EncodedRequest", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
