events {}

http {
    log_format xdn_bench '$request_method $uri [reqId=$http_x_xdn_reqid] [lat=${request_time}s]';
    access_log /dev/stdout xdn_bench;
    error_log /dev/stderr;

    server {
        listen 80;

        location /api/books {
            default_type application/json;
            return 200 '{"id":1,"title":"mock"}';
        }
    }
}
