APPLICATION=edu.umass.cs.xdn.XdnGigapaxosApp

GIGAPAXOS_DATA_DIR=/tmp/gigapaxos

ENABLE_ACTIVE_REPLICA_HTTP=true
ENABLE_RECONFIGURATOR_HTTP=true
BATCHING_ENABLED=true
REPLICA_COORDINATOR_CLASS=edu.umass.cs.xdn.XdnReplicaCoordinator
ENABLE_STARTUP_LEADER_ELECTION=false
HIBERNATE_OPTION=true
SYNC=true

# 768MB
# Needed for large non-deterministic state transfer packets 
# (observed ~663MB in logs).
NIO_MAX_PAYLOAD_SIZE=805306368

INITIAL_STATE_VALIDATOR_CLASS=edu.umass.cs.xdn.XdnServiceInitialStateValidator
INITIAL_STATE_NUM_REPLICAS_EXTRACTOR_CLASS=edu.umass.cs.xdn.XdnServiceNumReplicasExtractor
XDN_PB_STATEDIFF_RECORDER_TYPE=RSYNC
XDN_PB_ENABLE_NON_DETERMINISTIC_INIT=true

REPLICATE_ALL=false
EMULATE_UNREPLICATED=false
HTTP_AR_FRONTEND_BATCH_ENABLED=true
HTTP_AR_FRONTEND_REQUEST_TIMEOUT_MS=60000
XDN_HTTP_MAX_POOL_SIZE=128

# format: active.<active_server_name>=host:port
active.AR0=127.0.0.1:2000
active.AR1=127.0.0.1:2001
active.AR2=127.0.0.1:2002
active.AR3=127.0.0.1:2003
active.AR4=127.0.0.1:2004

# format: active.<active_server_name>.geolocation="latitude,longitude"
active.AR0.geolocation="39.5832,-82.3511"
active.AR1.geolocation="3.1490,37.0425"
active.AR2.geolocation="81.3236,11.4012"
active.AR3.geolocation="35.6895,139.6917"
active.AR4.geolocation="51.5074,-0.1278"

# format: reconfigurator.<active_server_name>=host:port
reconfigurator.RC0=127.0.0.1:3000
