FROM golang:1.21
WORKDIR /app

# import the codebase
ADD src ./src
COPY main.go ./

# prepare dependencies
COPY go.mod go.sum ./
RUN go mod download

# compile the codebase
RUN CGO_ENABLED=1 go build -o main -a -ldflags \
    '-linkmode external -extldflags "-static"' .

CMD ["./main"]
