# Generated by Django 5.1.7 on 2025-03-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='index',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='player', max_length=20),
        ),
    ]
