# Generated by Django 5.1.7 on 2025-03-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_player_index_remove_player_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
